### ISSUE TITLE
Typing error in generated ".d.ts" preventing usage

### ISSUE THREAD

**Issue by DropboxKenshiro** [onhate/nest-onetable#2]
Without any issue guidelines or template I'll try to write this issue as well as I can :)

When importing library into the project, the .d.ts files show following errors:
```
Type 'K' does not satisfy the constraint 'keyof Required<T> | keyof OptionalOrUndefined<T>'.
Type 'keyof T' is not assignable to type 'keyof Required<T> | keyof OptionalOrUndefined<T>'.
Type 'string | number | symbol' is not assignable to type 'keyof Required<T> | keyof OptionalOrUndefined<T>'. Type 'string' is not assignable to type 'keyof Required<T> | keyof OptionalOrUndefined<T>'.
```
all of those come from `decorators.d.ts`

This could obviously be skipped with TypeScript's `skipLibCheck` but it remains a problem to be fixed.
To replicate, simply create a new nest project, add the `nest-onetable` library and disable `skipLibCheck`.

**Comment by onhate** [comment]
hey, hi @DropboxKenshiro thanks for sharing this issues, I'll investigate it and let you know

**Comment by onhate** [comment]
I could not reproduce this issue @DropboxKenshiro
